// app/layout.tsx

import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { NotificationProvider } from "@/components/notificationContext/notificationContext";
import ToastContainer from "@/components/toastContainer/toastContainer";
import { createServerSupabaseClient } from "@/utils/supabaseServer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get server-side supabase session tokens and pass to client provider
  const supabase = await createServerSupabaseClient();
  const { data } = await supabase.auth.getSession();
  const accessToken = data?.session?.access_token ?? null;
  const refreshToken = data?.session?.refresh_token ?? null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider initialAccessToken={accessToken} initialRefreshToken={refreshToken}>
          <Header />
          <main>{children}</main>
          <ToastContainer />
        </NotificationProvider>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/header/header";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }